<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE datasources
    PUBLIC "-//JBoss//DTD JBOSS JCA Config 1.5//EN"
    "http://www.jboss.org/j2ee/dtd/jboss-ds_1_5.dtd">
    
<datasources>
   
   <local-tx-datasource>
   <jndi-name>fulltimeDatasource</jndi-name>
   <connection-url>jdbc:mysql://localhost:3306/fulltimebaca</connection-url>
      <driver-class>com.mysql.jdbc.Driver</driver-class>
      <user-name>root</user-name>
      <password>root</password>
<!-- 

		<jndi-name>fulltimeDatasource</jndi-name>
      <connection-url>jdbc:mysql://localhost:3306/fulltime</connection-url>
      <driver-class>com.mysql.jdbc.Driver</driver-class>
      <user-name>root</user-name>
      <password>root</password>
	  
	  <min-pool-size>2</min-pool-size>
	  <max-pool-size>25</max-pool-size>
	  <idle-timeout-minutes>5</idle-timeout-minutes>
		
		
      <jndi-name>fulltimeDatasource</jndi-name>
      <connection-url>jdbc:postgresql://localhost:5432/fulltime</connection-url>
      <driver-class>org.postgresql.Driver</driver-class>
      <user-name>postgres</user-name>
      <password>root</password>
      
         <jndi-name>fulltimeDatasource</jndi-name>
      <connection-url>jdbc:sqlserver://localhost:1433;DatabaseName=fulltime</connection-url>
      <driver-class>com.microsoft.sqlserver.jdbc.SQLServerDriver</driver-class>
      <user-name>full</user-name>
      <password>full</password>

      <exception-sorter-class-name>
         org.jboss.resource.adapter.jdbc.vendor.MySQLExceptionSorter
      </exception-sorter-class-name>
      <metadata>
         <type-mapping>mySQL</type-mapping>
      </metadata>
-->
   </local-tx-datasource>
    
</datasources>

